version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Updated to reflect new directory structure
      dockerfile: Dockerfile  # Ensure Dockerfile is located within the backend directory
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    environment:
      DATABASE_HOST: db  # Use service name for DB host
      DATABASE_USER: ${DB_USER}
      DATABASE_NAME: ${DB_NAME}
      ELASTICSEARCH_HOST: elasticsearch
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.port=9200
      - "http.cors.allow-origin=http://localhost"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

  frontend:
    build: ./frontend  # Correct path to your frontend application
    ports:
      - "3000:80"  # Map port 80 inside the container to port 3000 on the host
    volumes:
      - ./frontend:/app  # Correct mapping of the frontend directory
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend  # Depends on the backend service
      - elasticsearch

volumes:
  postgres-data:
  elasticsearch-data:

networks:
  app-network:
